## Autograd

In [20]:
import torch
from torch import nn

In [21]:
x = torch.randn(2,2, requires_grad=True)
x

tensor([[-0.1135,  0.1071],
        [ 0.9417,  0.3415]], requires_grad=True)

In [22]:
y=x+2
y

tensor([[1.8865, 2.1071],
        [2.9417, 2.3415]], grad_fn=<AddBackward0>)

In [23]:
z=y*y*2
# z = z.mean()
z

tensor([[ 7.1174,  8.8796],
        [17.3066, 10.9657]], grad_fn=<MulBackward0>)

In [24]:
v= torch.tensor([[1,2],[3,4]])
v
z.backward(v) #dz/dx
x.grad

tensor([[ 7.5458, 16.8567],
        [35.2998, 37.4647]])

In [ ]:
# stop gradient

x = torch.randn(3, requires_grad=True)
# x.requires_grad_(False)
# x.detach_()
# with torch.no_grad():
#     x

In [36]:
weights = torch.ones(2, requires_grad=True)

for epoch in range(2):
    model_output = (weights*3).sum()
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()

tensor([3., 3.])
tensor([3., 3.])


In [41]:
# optimizer = torch.optim.SGD(weights, lr=0.01)
# optimizer.step()
# optimizer.zero_grad()